### ISSUE TITLE
Maximum Page limit does not exceed 4000

### ISSUE THREAD

**Issue by Aniconomics** [KurtBestor/Hitomi-Downloader#7097]
![Clllllllllapture](https://github.com/KurtBestor/Hitomi-Downloader/assets/65483331/6fe6c03d-56a3-45a6-ae36-398c7d62521a)

![Cap ppture](https://github.com/KurtBestor/Hitomi-Downloader/assets/65483331/f2b69062-a7d5-4494-886e-f93b69077186)

The tag I am downloading from has 5.6k uploads and future tags will likely exceed 10k. I increased the page limit to 10,000 but the link shows 4000 and stops downloading at 4000.

**Comment by rickmiron** [comment]
Version J is a double-edged sword, since it does not analyze the total number of images, it places a limit of 4000 since Hitomi Downloader requires that you indicate how many files are going to be downloaded.
you can start a new download from the point you left off:
example:
suppose this tag has 10000 files
https://chan.sankakucomplex.com/en/?tags=examples
It will only download the first 4000
Let's assume that the smallest number that was downloaded is 99955.jpg
then you can continue the download with this link
https://chan.sankakucomplex.com/en/?tags=examples+id_range%3A%3C99955
which will download the next 4000 files
and repeat the process until all the files are downloaded, in this case it would be 10,000


or you can open the plugin and search for 4000 and replace it with the limit you want

**Comment by Aniconomics** [comment]
Using the tag before as a reference and your advice. I need to type out "kawakami_rokkaku id_range:<12469064" in the search bar and past the resulting link in hitomi
